---
image: Visual Studio 2017
build: false
version: '{build}'

platform:
  - x64

environment:
  matrix:
#    - TARGET: x86_64-pc-windows-gnu
#      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set PATH=C:\msys64\usr\bin;%PATH%
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S automake autoconf texinfo mingw-w64-x86_64-clang libtool"
  - rustc -Vv
  - cargo -V
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

cache:
  - C:\Users\appveyor\.cargo
  - compiler\vendor

test_script:
  - C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash -lc 'cd $APPVEYOR_BUILD_FOLDER; cargo build --verbose'
  - C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash -lc 'cd $APPVEYOR_BUILD_FOLDER; cargo test'
