status = [
    "Audit",
    "Code lint",
    "Test on linux-x64",
    # "Test on linux-musl-x64",
    # "Test on linux-aarch64",
    "Test on macos-x64",
    "Test on windows-x64",
    "Test cross-compile on linux",
    "Test cross-compile on macos",
]
required_approvals = 0
timeout_sec = 7200
delete_merged_branches = true
