status = [
    "ci/circleci: lint",
    "ci/circleci: test",
    "ci/circleci: test-macos",
    "ci/circleci: test-stable",
    "continuous-integration/appveyor/branch"
]
required_approvals = 1
timeout_sec = 900
delete_merged_branches = true 
