[package]
name = "vfs-core"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-lock.workspace = true
async-trait.workspace = true
bitflags.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
vfs-ratelimit = { path = "../ratelimit" }

[dev-dependencies]
vfs-rt = { path = "../rt" }
futures.workspace = true
vfs-mem = { path = "../mem" }
