[package]
name = "vfs-rt"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
futures.workspace = true
vfs-core = { path = "../core" }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"], optional = true }

[features]
tokio = ["dep:tokio"]
