name: Run Benchmarks and upload results

on:
  push:
    branches:
    - benchmark  # TODO: change it back to master once we really track the results. We commented this as speed.wasmer.io is failing

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
  MSRV: "1.73"

jobs:
  run_benchmark:
    name: Benchmark on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
    env:
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
      - name: Configure cargo data directory
        # After this point, all cargo registry and crate data is stored in
        # $GITHUB_WORKSPACE/.cargo_home. This allows us to cache only the files
        # that are needed during the build process. Additionally, this works
        # around a bug in the 'cache' action that causes directories outside of
        # the workspace dir to be saved/restored incorrectly.
        run: echo "CARGO_HOME=$(pwd)/.cargo_home" >> $GITHUB_ENV
      - name: Cache
        uses: actions/cache@master
        with:
          # Note: crates from the git repo always get rebuilt
          # so we cache only those subdirectories of target/{debug|release} that
          # contain the build output for crates that come from the registry.
          path: |-
            .cargo_home
            target/*/.*
            target/*/build
            target/*/deps
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}
      - name: Install LLVM (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz -L -o llvm.tar.xz
          mkdir -p /opt/llvm-10
          tar xf llvm.tar.xz --strip-components=1 -C /opt/llvm-10
          echo '/opt/llvm-10/bin' >> $GITHUB_PATH
          echo 'name=LLVM_SYS_100_PREFIX=/opt/llvm-10' >> $GITHUB_ENV
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install codespeed-client
          pip install toml
      - name: Run Benchmark
        run: |
          make bench
          git clone https://github.com/wasmerio/wasmer-bench

          python3 wasmer-bench/send_metrics.py

