name: Release cloudcompiler.wasm

env:
  RUST_BACKTRACE: 1
  MSRV: "1.81"

on:
  push:
    tags:
      # trigger action on release branch
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          target: ${{ matrix.target }}
      - name: Install wasm32-wasip1 target
        shell: bash
        run: |
          rustup target add wasm32-wasip1
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1
      - name: Build cloudcompiler.wasm
        shell: bash
        run: |
          make build-wasmer-wasm &&
          mkdir target/wasm32-wasip1/release/cloudcompiler
          cp target/wasm32-wasip1/release/wasmer-compiler.wasm target/wasm32-wasip1/release/cloudcompiler/cloudcompiler.wasm &&
          cat << EOF > target/wasm32-wasip1/release/cloudcompiler/wasmer.toml
          [package]
          name = "${{ secrets.WAPM_DEV_USERNAME }}/cloudcompiler"
          version = "0.1.0"
          description = "cloudcompiler.wasm"
          license = "MIT"
          repository = "https://github.com/wasmerio/wasmer"

          [[module]]
          name = "cloudcompiler"
          source = "cloudcompiler.wasm"
          abi = "wasi"

          [module.interfaces]
          wasi = "0.1.0-unstable"

          [[command]]
          name = "cloudcompiler"
          module = "cloudcompiler"
          EOF
      - name: Fix wasmer.toml version
        run: |
          echo $(git tag | tail -n1) > ./version.txt
          v=$(git describe --tags --abbrev=0) && \
          echo "version = ${v}" &&
          sed -i "s/version = \".*\"/version = \"${v}\"/g" target/wasm32-wasip1/release/cloudcompiler/wasmer.toml \
      - name: Build cloudcompiler.wasm
        shell: bash
        run: |
          git tag &&
          cat target/wasm32-wasip1/release/cloudcompiler/wasmer.toml &&
          echo "ls" &&
          ls target/wasm32-wasip1/release/cloudcompiler
      - name: Publish to WAPM
        uses: wasmerio/wapm-publish@v1
        with:
          registry: https://registry.wapm.dev
          directory: target/wasm32-wasip1/release/cloudcompiler
          username: ${{ secrets.WAPM_DEV_USERNAME }}
          password: ${{ secrets.WAPM_DEV_PASSWORD }}
