name: core tests

env:
  RUST_BACKTRACE: 1

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'trying'
    tags:
      # this is _not_ a regex, see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.setup.outputs.VERSION }}
      DOING_RELEASE: ${{ steps.setup.outputs.DOING_RELEASE }}
    steps:
      - name: Set up env vars
        id: setup
        shell: bash
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${VERSION}
          DOING_RELEASE=$(echo $VERSION | grep -c '[0-9]\+\.[0-9]\+\.[0-9]\+\(-.*\)\?' || true)
          echo ::set-output name=DOING_RELEASE::${DOING_RELEASE}
          echo $VERSION
          echo $DOING_RELEASE

  test:
    name: Test on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        build: [linux, macos, windows, linux-arm]
        include:
          - build: linux
            os: ubuntu-latest
            rust: 1.45.2
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz'
            artifact_name: 'wasmer-linux-amd64'
          - build: macos
            os: macos-latest
            rust: 1.45.2
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz'
            artifact_name: 'wasmer-macos-amd64'
          - build: windows
            os: windows-latest
            rust: 1.45.2
            artifact_name: 'wasmer-windows-amd64'
          - build: linux-arm
            os: [self-hosted, linux, ARM64]
            rust: 1.45.2
            llvm_url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-aarch64-linux-gnu.tar.xz'
            artifact_name: 'wasmer-linux-aarch64'
    env:
      CARGO_SCCACHE_VERSION: 0.2.13
      SCCACHE_AZURE_BLOB_CONTAINER: wasmerstoragesccacheblob
      SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Configure cargo data directory
        # After this point, all cargo registry and crate data is stored in
        # $GITHUB_WORKSPACE/.cargo_home. This allows us to cache only the files
        # that are needed during the build process. Additionally, this works
        # around a bug in the 'cache' action that causes directories outside of
        # the workspace dir to be saved/restored incorrectly.
        run: echo "::set-env name=CARGO_HOME::$(pwd)/.cargo_home"
      - name: Cache
        uses: actions/cache@master
        with:
          # Note: crates from the git repo always get rebuilt
          # so we cache only those subdirectories of target/{debug|release} that
          # contain the build output for crates that come from the registry.
          path: |-
            .cargo_home
            target/*/.*
            target/*/build
            target/*/deps
          key: ${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.rust }}-
      # # Install sccache
      # - uses: actions/cache@master
      #   with:
      #     path: ${{ runner.tool_cache }}/cargo-sccache
      #     key: cargo-sccache-bin-${{ env.CARGO_SCCACHE_VERSION }}
      # - name: Install sccache
      #   run: |
      #     echo "::add-path::${{ runner.tool_cache }}/cargo-sccache/bin"
      #     cargo install sccache --version ${{ env.CARGO_SCCACHE_VERSION }} --root ${{ runner.tool_cache }}/cargo-sccache
      # - name: Start sccache
      #   run: |
      #     ${{ runner.tool_cache }}/cargo-sccache/bin/sccache --start-server
      #     ${{ runner.tool_cache }}/cargo-sccache/bin/sscache -s
      #     echo "::set-env name=RUSTC_WRAPPER::${{ runner.tool_cache }}/cargo-sccache/bin/sccache"
      - name: Install LLVM (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install llvm
        # run: |
        #   curl --proto '=https' --tlsv1.2 -sSf https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe -L -o llvm-installer.exe
        #   7z x llvm-installer.exe -oC:/llvm-10
        #   echo ::add-path::C:/llvm-10/bin
        #   echo ::set-env name=LLVM_SYS_100_PREFIX::C:/llvm-10
        #   echo ::set-env name=LIBCLANG_PATH::C:/llvm-10/bin/libclang.dll
      - name: Install LLVM (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf ${{ matrix.llvm_url }} -L -o llvm.tar.xz
          mkdir -p ${{ env.LLVM_DIR }}
          tar xf llvm.tar.xz --strip-components=1 -C ${{ env.LLVM_DIR }}
          echo "::add-path::${{ env.LLVM_DIR }}/bin"
          echo "::set-env name=LLVM_SYS_100_PREFIX::${{ env.LLVM_DIR }}"
        env:
          LLVM_DIR: ${{ github.workspace }}/llvm-10
      - name: Set up dependencies for Mac OS
        run: brew install automake
        if: matrix.os == 'macos-latest'
      - run: make test
      - name: Build and Test C API
        run: |
          make build-capi
          make test-capi-cranelift
        if: matrix.os != 'windows-latest'
      - name: Build C API on Windows
        run: make build-capi
        if: matrix.os == 'windows-latest'
      - name: Build Wasmer binary
        run: |
          make build-wasmer
      - name: Build Wapm binary
        run: |
          make build-wapm
        if: needs.setup.outputs.DOING_RELEASE == '1'
      - name: Package Wasmer
        run: |
          make package
        if: needs.setup.outputs.DOING_RELEASE == '1'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: needs.setup.outputs.DOING_RELEASE == '1'
        with:
          name: ${{ matrix.artifact_name }}
          path: dist

  release:
    needs: [setup, test]
    runs-on: ubuntu-latest
    if: needs.setup.outputs.DOING_RELEASE == '1'
    steps:
      - name: Download the Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.setup.outputs.VERSION }}
          release_name: Release ${{ needs.setup.outputs.VERSION }}
          draft: true
          prerelease: false
      - name: Upload Release Asset Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: artifacts/wasmer-windows-amd64/wasmer-windows.exe
          asset_name: wasmer-windows.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload Release Asset Linux amd64
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/wasmer-linux-amd64/wasmer-linux-amd64.tar.gz
          asset_name: wasmer-linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset Mac
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/wasmer-macos-amd64/wasmer-darwin-amd64.tar.gz
          asset_name: wasmer-darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset Linux aarch64
        id: upload-release-asset-linux-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/wasmer-linux-aarch64/wasmer-linux-aarch64.tar.gz
          asset_name: wasmer-linux-aarch64.tar.gz
          asset_content_type: application/gzip

  audit:
    name: Audit
    env:
      CARGO_AUDIT_VERSION: 0.12.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@master
        with:
          path: ${{ runner.tool_cache }}/cargo-audit
          key: cargo-audit-bin-${{ env.CARGO_AUDIT_VERSION }}
      - run: |
          echo "::add-path::${{ runner.tool_cache }}/cargo-audit/bin"
      - run: |
          cargo install cargo-audit --version ${{ env.CARGO_AUDIT_VERSION }} --root ${{ runner.tool_cache }}/cargo-audit
          cargo audit
